export const IPC_CHANNELS = {
  listPairs: "desktop:listPairs",
  status: "desktop:status",
  pairStatus: "desktop:pairStatus",
  pairDetail: "desktop:pairDetail",
  pausePair: "desktop:pausePair",
  resumePair: "desktop:resumePair",
  startPair: "desktop:startPair",
  stopPair: "desktop:stopPair",
  startAll: "desktop:startAll",
  stopAll: "desktop:stopAll",
  validatePair: "desktop:validatePair",
  getValidation: "desktop:getValidation",
  getRecentEvents: "desktop:getRecentEvents",
  getAutomationInfo: "desktop:automation:info",
  seedPlanner: "desktop:automation:seed-planner",
  feedLocalAgent: "desktop:automation:feed-local-agent",
  listOpenCodeSessions: "desktop:listOpenCodeSessions",
  createPair: "desktop:pairs:create",
  updatePair: "desktop:pairs:update",
  removePair: "desktop:pairs:remove",
  rebindWorker: "desktop:pairs:rebindWorker",
  suggestWorkerSessionTitle: "desktop:pairs:suggest-worker-session-title",
  createWorkerSessionForPair: "desktop:pairs:create-worker-session",
  openWorkerSession: "desktop:pairs:open-worker-session",
  listWorkerQuestions: "desktop:worker:questions",
  getWorkerTranscript: "desktop:worker:transcript",
  answerWorkerQuestion: "desktop:worker:answer-question",
  listWorkerModels: "desktop:worker:models",
  switchWorkerModel: "desktop:worker:switch-model",
  resumeWithFallbackModel: "desktop:worker:resume-with-fallback-model",
  validateCandidate: "desktop:pairs:validate-candidate",
  discoverWorkerSessions: "desktop:worker:sessions",
  scanDesktopWorkerSession: "desktop:worker:scan-desktop",
  alignWorkerSessionWithOpenCodeDesktop: "desktop:worker:align-desktop-session",
  startWorkerServer: "desktop:worker:start-server",
  updateOpenCode: "desktop:worker:update-opencode",
  createWorkerSession: "desktop:worker:create",
  testWorkerEndpoint: "desktop:worker:test",
  getOpenCodeEndpoint: "desktop:worker:endpoint",
  parsePlannerUrl: "desktop:planner:parse-url",
  testPlannerEndpoint: "desktop:planner:test",
  startPlannerBrowser: "desktop:planner:start-browser",
  getChatGptEndpoint: "desktop:planner:endpoint",
  getWorkerProgress: "desktop:worker:progress",
  startProject: "desktop:project:start",
  pauseProject: "desktop:project:pause",
  resumeProject: "desktop:project:resume",
  getTimeline: "desktop:timeline",
  listProjectPairs: "desktop:project-pairs:list",
  createProjectPair: "desktop:project-pairs:create",
  removeProjectPair: "desktop:project-pairs:remove",
  discoverOpenCodeProjects: "desktop:project-pairs:discover-opencode-projects",
  discoverChatGptProjects: "desktop:project-pairs:discover-chatgpt-projects",
  listArchive: "desktop:archive:list",
  deleteArchive: "desktop:archive:delete",
  copyText: "desktop:copy-text",
  event: "desktop:event"
} as const;

export type IpcChannel = (typeof IPC_CHANNELS)[keyof typeof IPC_CHANNELS];

export const ALLOWED_INVOKE_CHANNELS: readonly string[] = [
  IPC_CHANNELS.listPairs,
  IPC_CHANNELS.status,
  IPC_CHANNELS.pairStatus,
  IPC_CHANNELS.pairDetail,
  IPC_CHANNELS.pausePair,
  IPC_CHANNELS.resumePair,
  IPC_CHANNELS.startPair,
  IPC_CHANNELS.stopPair,
  IPC_CHANNELS.startAll,
  IPC_CHANNELS.stopAll,
  IPC_CHANNELS.validatePair,
  IPC_CHANNELS.getValidation,
  IPC_CHANNELS.getRecentEvents,
  IPC_CHANNELS.getAutomationInfo,
  IPC_CHANNELS.seedPlanner,
  IPC_CHANNELS.feedLocalAgent,
  IPC_CHANNELS.listOpenCodeSessions,
  IPC_CHANNELS.createPair,
  IPC_CHANNELS.updatePair,
  IPC_CHANNELS.removePair,
  IPC_CHANNELS.rebindWorker,
  IPC_CHANNELS.suggestWorkerSessionTitle,
  IPC_CHANNELS.createWorkerSessionForPair,
  IPC_CHANNELS.openWorkerSession,
  IPC_CHANNELS.listWorkerQuestions,
  IPC_CHANNELS.getWorkerTranscript,
  IPC_CHANNELS.answerWorkerQuestion,
  IPC_CHANNELS.listWorkerModels,
  IPC_CHANNELS.switchWorkerModel,
  IPC_CHANNELS.resumeWithFallbackModel,
  IPC_CHANNELS.validateCandidate,
  IPC_CHANNELS.discoverWorkerSessions,
  IPC_CHANNELS.scanDesktopWorkerSession,
  IPC_CHANNELS.alignWorkerSessionWithOpenCodeDesktop,
  IPC_CHANNELS.startWorkerServer,
  IPC_CHANNELS.updateOpenCode,
  IPC_CHANNELS.createWorkerSession,
  IPC_CHANNELS.testWorkerEndpoint,
  IPC_CHANNELS.getOpenCodeEndpoint,
  IPC_CHANNELS.parsePlannerUrl,
  IPC_CHANNELS.testPlannerEndpoint,
  IPC_CHANNELS.startPlannerBrowser,
  IPC_CHANNELS.getChatGptEndpoint,
  IPC_CHANNELS.getWorkerProgress,
  IPC_CHANNELS.getTimeline,
  IPC_CHANNELS.startProject,
  IPC_CHANNELS.pauseProject,
  IPC_CHANNELS.resumeProject,
  IPC_CHANNELS.listProjectPairs,
  IPC_CHANNELS.createProjectPair,
  IPC_CHANNELS.removeProjectPair,
  IPC_CHANNELS.discoverOpenCodeProjects,
  IPC_CHANNELS.discoverChatGptProjects,
  IPC_CHANNELS.listArchive,
  IPC_CHANNELS.deleteArchive,
  IPC_CHANNELS.copyText
];

export const EVENT_CHANNEL = IPC_CHANNELS.event;

export const STATUS_REFRESH_CHANNEL = "desktop:status-refresh";

export const WORKER_PROGRESS_CHANNEL = "desktop:worker-progress-update";
